services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - banco_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banco"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  auth-server:
    build: ./auth-server
    ports:
      - "9000:9000"

  clientes-service:
    build: ./clientes-service
    ports:
      - "8091:8091"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server
    restart: on-failure

  cuentas-service:
    build: ./cuentas-service
    ports:
      - "8092:8092"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - config-server
      - eureka-server
    restart: on-failure

  bank-batch:
    build: ./bank-batch
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banco
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://auth-server:9000/oauth2/jwks
      CLIENTES_URL: http://clientes-service:8091
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      config-server:
        condition: service_started
      eureka-server:
        condition: service_started
      auth-server:
        condition: service_started
    restart: on-failure

volumes:
  banco_data: