spring.application.name=auth-server
server.port=9000

# Client: canal WEB
spring.security.oauth2.authorizationserver.client.web.registration.client-id=web
spring.security.oauth2.authorizationserver.client.web.registration.client-secret={noop}web123
spring.security.oauth2.authorizationserver.client.web.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.web.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.web.registration.scopes=web

# Client: canal MOVIL
spring.security.oauth2.authorizationserver.client.movil.registration.client-id=movil
spring.security.oauth2.authorizationserver.client.movil.registration.client-secret={noop}movil123
spring.security.oauth2.authorizationserver.client.movil.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.movil.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.movil.registration.scopes=movil

# Client: canal CAJERO
spring.security.oauth2.authorizationserver.client.cajero.registration.client-id=cajero
spring.security.oauth2.authorizationserver.client.cajero.registration.client-secret={noop}cajero123
spring.security.oauth2.authorizationserver.client.cajero.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.cajero.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.cajero.registration.scopes=cajero