spring.application.name=bank-batch

spring.datasource.url=jdbc:postgresql://localhost:5433/banco
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.batch.jdbc.initialize-schema=never
spring.batch.job.enabled=false

# ---------------------------------------------
# HTTPS
# ---------------------------------------------
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:bank-batch.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bank-batch

# --- Spring Cloud: Config Server ---
spring.config.import=optional:configserver:http://localhost:8888

# --- Spring Cloud: Eureka ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.instances.clientesService.sliding-window-size=5
resilience4j.circuitbreaker.instances.clientesService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.clientesService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.clientesService.wait-duration-in-open-state=5000

# ---------------------------------------------
# KAFKA
# ---------------------------------------------
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=bank-batch-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ---------------------------------------------
# MENSAJERIA
# ---------------------------------------------
mensaje.origen=bank-batch

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_JWK_URI:http://localhost:9000/oauth2/jwks}

resilience4j.retry.instances.clientesService.max-attempts=3
resilience4j.retry.instances.clientesService.wait-duration=500ms
resilience4j.bulkhead.instances.clientesService.max-concurrent-calls=5
resilience4j.bulkhead.instances.clientesService.max-wait-duration=0